---  
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
    
- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
      - npm
      - nodejs
      - git

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
#    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
