- name: "Move files to server"
  copy:
    src: /root/project/backend/
    dest: /home/ubuntu/app

- name: "Install app dependencies"
  shell: |
    cd /home/ubuntu/app
    npm install

- name: "Build package"
  shell: |
    cd /home/ubuntu/app
    npm run build

- name: Start application
  become: true
  shell: |
    cd /home/ubuntu/app
    pm2 start npm --name backend -- run "start:prod"
